name: Linux Build

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string

jobs:
  build:
    name: Linux ${{ inputs.config }} Build
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: >
          azure.archive.ubuntu.com:80
          boringssl.googlesource.com:443
          github.com:443
          pipelines.actions.githubusercontent.com:443

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        submodules: recursive

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - name: Configure CMake
      run: cmake --preset linux-${{ inputs.config }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset linux-${{ inputs.config }}

    - name: Upload
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      if: ${{ !failure() }}
      with:
        name: linux-${{ inputs.config }}-${{ github.sha }}
        path: ${{ github.workspace }}/out/bin/linux-${{ inputs.config }}/*
