name: Pull Request CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-windows-debug:
    uses: ./.github/workflows/windows.yml
    with:
      config: debug
  build-windows-release:
    uses: ./.github/workflows/windows.yml
    with:
      config: release
  build-linux-debug:
    uses: ./.github/workflows/linux.yml
    with:
      config: debug
  build-linux-release:
    uses: ./.github/workflows/linux.yml
    with:
      config: release

    #- name: Test
      #working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      
