name: Pull Request CI

on:
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: debug

jobs:
  build:
    name: Build
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        config: [debug, release]

    uses: ./.github/workflows/windows.yml
    if: ${{ matrix.os == windows-latest }}
    with:
      config: ${{ matrix.config }}

    uses: ./.github/workflows/linux.yml
    if: ${{ matrix.os == ubuntu-latest }}
    with:
      config: ${{ matrix.config }}

    - name: Copy Files (Windows)
      if: ${{ matrix.os_family == 'windows' && !failure() }}
      run: |
            mkdir ${{ github.workspace }}/latest
            copy ${{ github.workspace }}/out/bin/${{ matrix.os_family }}-${{ env.BUILD_TYPE }}/quiccat.exe ${{ github.workspace }}/latest
            copy ${{ github.workspace }}/out/bin/${{ matrix.os_family }}-${{ env.BUILD_TYPE }}/quiccat.pdb ${{ github.workspace }}/latest
            7z.exe a ${{ github.workspace }}/latest-${{ matrix.os_family }}.zip ${{ github.workspace }}/latest

    - name: Copy Files (Linux)
      if: ${{ matrix.os_family == 'linux' && !failure() }}
      run: |
            mkdir ${{ github.workspace }}/latest
            cp ${{ github.workspace }}/out/bin/${{ matrix.os_family }}-${{ env.BUILD_TYPE }}/quiccat ${{ github.workspace }}/latest
            tar -cvf ${{ github.workspace }}/latest-${{ matrix.os_family }}.tar.gz ${{ github.workspace }}/latest

    - name: Update tag
      uses: EndBug/latest-tag@v1.4.0
      if: ${{ !failure() && github.ref == 'refs/heads/master' }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ !failure() && github.ref == 'refs/heads/master' }}
      with:
        files: ${{ github.workspace }}/latest-*
        name: Latest
        tag_name: latest

    #- name: Test
      #working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      
