name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-windows-debug:
    uses: ./.github/workflows/windows.yml
    with:
      config: debug
  build-windows-release:
    uses: ./.github/workflows/windows.yml
    with:
      config: release
  build-linux-debug:
    uses: ./.github/workflows/linux.yml
    with:
      config: debug
  build-linux-release:
    uses: ./.github/workflows/linux.yml
    with:
      config: release

  test-windows-debug:
    name: Test Windows Debug
    needs: [ build-windows-debug ]
    uses: ./.github/workflows/test.yml
    with:
      config: debug
      os: windows-latest
      os-family: windows

  test-windows-release:
    name: Test Windows Release
    needs: [ build-windows-release ]
    uses: ./.github/workflows/test.yml
    with:
      config: release
      os: windows-latest
      os-family: windows

  test-linux-debug:
    name: Test Linux Debug
    needs: [ build-linux-debug ]
    uses: ./.github/workflows/test.yml
    with:
      config: debug
      os: ubuntu-latest
      os-family: linux

  test-linux-release:
    name: Test Linux Release
    needs: [ build-linux-release ]
    uses: ./.github/workflows/test.yml
    with:
      config: release
      os: ubuntu-latest
      os-family: linux

    #- name: Test
      #working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      
