name: Release CI

on:
  push:
    branches: [ master ]

jobs:
  build-windows-release:
    uses: ./.github/workflows/windows.yml
    with:
      config: release

  build-linux-release:
    uses: ./.github/workflows/linux.yml
    with:
      config: release

  release-windows:
    name: Create Windows Release
    runs-on: windows-latest
    needs: build-windows-release

    - uses: actions/download-artifact@v3
      with:
        name: windows-release-${{ github.sha }}
        path: ${{ github.workspace }}/windows-latest

    - name: Compress Files
      run: |
            7z.exe a ${{ github.workspace }}/quiccat-latest-windows.zip ${{ github.workspace }}/windows-latest

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        files: ${{ github.workspace }}/quiccat-latest-*
        name: Latest
        tag_name: latest

  release-linux:
    name: Create Linux Release
    runs-on: ubuntu-latest
    needs: build-linux-release

    - uses: actions/download-artifact@v3
      with:
        name: linux-release-${{ github.sha }}
        path: ${{ github.workspace }}/linux-latest

    - name: Compress Files
      run: |
            tar -cvf ${{ github.workspace }}/quiccat-latest-linux.tar.gz ${{ github.workspace }}/linux-latest

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        files: ${{ github.workspace }}/quiccat-latest-*
        name: Latest
        tag_name: latest

  update-tag:
    needs: [release-windows, release-linux]
    runs-on: ubuntu-latest
    - name: Update tag
      uses: EndBug/latest-tag@v1.4.0
      if: ${{ github.ref == 'refs/heads/master' }}