name: Release CI

on:
  push:
    branches: [ master ]

jobs:
  build-windows-release:
    uses: ./.github/workflows/windows.yml
    with:
      config: release
  build-linux-release:
    uses: ./.github/workflows/linux.yml
    with:
      config: release
  test-windows-release:
    name: Test Windows Release
    needs: [ build-windows-release ]
    uses: ./.github/workflows/test.yml
    with:
      config: release
      os: windows-latest
      os-family: windows
  test-linux-release:
    name: Test Linux Release
    needs: [ build-linux-release ]
    uses: ./.github/workflows/test.yml
    with:
      config: release
      os: ubuntu-latest
      os-family: linux
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    needs: [ test-linux-release, test-windows-release ]
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        config: [ release ]
        include:
        - os: windows-latest
          os_family: windows
        - os: ubuntu-latest
          os_family: linux
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.os_family }}-${{ matrix.config }}-${{ github.sha }}
        path: ${{ github.workspace }}/${{ matrix.os_family }}-latest

    - name: Compress Files (Windows)
      if: ${{ matrix.os_family == 'windows'}}
      run: |
            7z.exe a ${{ github.workspace }}/quiccat-latest-${{ matrix.os_family }}.zip ${{ matrix.os_family }}-latest

    - name: Compress Files (Linux)
      if: ${{ matrix.os_family == 'linux'}}
      run: |
            tar -cvf ${{ github.workspace }}/quiccat-latest-${{ matrix.os_family }}.tar.gz ${{ matrix.os_family }}-latest

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        files: ${{ github.workspace }}/quiccat-latest-*
        name: Latest
        tag_name: latest

  update-tag:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update tag
      uses: EndBug/latest-tag@v1.4.0
      if: ${{ github.ref == 'refs/heads/master' }}
