name: Windows Build

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string

jobs:
  build:
    name: Windows ${{ inputs.config }} Build
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        submodules: recursive
    - uses: ilammy/setup-nasm@229bfed4a21b01237d340787ea51fd7c50a49c54
    - uses: ilammy/msvc-dev-cmd@d8610e2b41c6d0f0c3b4c46dad8df0fd826c68e1

    - name: Install Ninja
      run: |
            choco install ninja
            ninja.exe --version

    - name: Configure CMake
      run: cmake --preset windows-${{ inputs.config }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset windows-${{ inputs.config }}

    - name: Upload
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      if: ${{ !failure() }}
      with:
        name: windows-${{ inputs.config }}-${{ github.sha }}
        path: ${{ github.workspace }}/out/bin/windows-${{ inputs.config }}/*
